"""How to Import into OpenOLAT documentation page for QTI-Creator."""

import gradio as gr

OPENOLAT_MARKDOWN = """
## 🚀 Using your QTI test in OpenOlat

QTI-Creator generates an **IMS QTI 2.1 test package** that can be imported directly into OpenOlat.

The simplest way to use it is to import the generated ZIP directly into a **Test** or **Self-test** course element.

### Quickest route: add the test directly to a course

1. In QTI-Creator, click **📦 Generate OpenOLAT QTI Package** and download the generated `.zip` file.
2. Open your course in OpenOlat and enter the **Course editor**.
3. Add a **Test** or **Self-test** course element.
4. Open its **Test configuration**.
5. Choose the option to **select or import a test** and import the `.zip` generated by QTI-Creator.
6. Configure the test options you need.
7. Publish the course.
"""


def render_openolat_page() -> None:
    """Render the OpenOLAT Import documentation page."""
    with gr.Column(elem_classes=["docs-content"]):
        gr.Markdown(OPENOLAT_MARKDOWN)

        with gr.Accordion("▶ Step-by-step: Course element import", open=False):
            gr.Markdown(
                """
                ### Test vs. Self-test in OpenOlat

                | Element | Intended use | Grading / Attempts |
                |---|---|---|
                | **Test** | Graded or summative assessments | Attempts can be limited; results are stored in the assessment tool |
                | **Self-test** | Formative practice and self-assessment | Can usually be repeated without affecting grades |

                ### Importing the package

                1. In the OpenOlat course editor, insert a **Test** or **Self-test** element.
                2. In the element settings, go to the **Test configuration** tab.
                3. Click **Select, replace or import test**.
                4. Select **Import** and upload the `.zip` file downloaded from QTI-Creator.
                5. Enter a title for the imported learning resource (this will become your reusable test in OpenOlat).
                6. Save and close the configuration.

                📖 OpenOlat documentation: <a href="https://docs.openolat.org/manual_user/learningresources/Course_Elements/#test" target="_blank" rel="noopener noreferrer">Test course element</a>
                """
            )

        with gr.Accordion("▶ Alternative: Import into Authoring area", open=False):
            gr.Markdown(
                """
                If you prefer to manage the test as an independent learning resource before adding it to a course:

                1. Go to the OpenOlat main menu and choose **Authoring**.
                2. Click **Import** (or **Create / Import**).
                3. Choose **Import file**.
                4. Upload the `.zip` generated by QTI-Creator.
                5. OpenOlat imports the package as a **Test** learning resource.
                6. You can now inspect, configure, and share this test independently of any single course.

                To use it later in a course:
                - Add a **Test** course element.
                - Under **Test configuration**, click **Select, replace or import test**.
                - Choose the existing test resource from your list.

                📖 OpenOlat documentation: <a href="https://docs.openolat.org/manual_user/learningresources/Creating_learning_resources/" target="_blank" rel="noopener noreferrer">Creating and importing learning resources</a>
                """
            )

        with gr.Accordion("▶ Alternative: Import questions into Question Bank", open=False):
            gr.Markdown(
                """
                If you want to manage individual questions rather than a complete test:

                1. Go to the OpenOlat main menu and choose **Question Bank**.
                2. Select **Import** from the actions menu.
                3. Choose **QTI 2.1 test**.
                4. Upload the `.zip` generated by QTI-Creator.
                5. OpenOlat imports the QTI 2.1 questions from the package into the Question Bank.

                The Question Bank is useful when you want to organize questions into pools or lists, edit individual questions, or reuse them when constructing other tests.

                OpenOlat also supports importing questions from an existing Test learning resource in the Authoring area.

                📖 OpenOlat documentation: <a href="https://docs.openolat.org/manual_user/area_modules/Question_Bank_Import_Questions/" target="_blank" rel="noopener noreferrer">Import questions into the Question Bank</a>
                """
            )

        with gr.Accordion("▶ Understanding tests in OpenOlat", open=False):
            gr.Markdown(
                """
                There are three useful ways to think about the generated QTI package:

                ### Test / Self-test course element
                A **course element** is where learners encounter the test inside a course. For the quickest workflow, add a Test or Self-test course element and import the QTI-Creator package there.

                ### Test learning resource
                The **Test learning resource** contains the test itself. Learning resources can be managed independently in the Authoring area and reused in courses.

                ### Question Bank
                The **Question Bank** manages individual questions. Use it when you want to reuse, organize, or edit questions independently of the complete test.

                | Your goal | Recommended route |
                |---|---|
                | Put this quiz into a course | **Course → Test / Self-test → Import** |
                | Keep a reusable complete test | **Authoring → Import file** |
                | Manage or reuse individual questions | **Question Bank → Import** |

                ```text
                QTI-Creator
                     │
                     ▼
                QTI 2.1 ZIP
                     │
                     ├──► Course → Test / Self-test
                     │         quickest route
                     │
                     ├──► Authoring → Test learning resource
                     │         reusable complete test
                     │
                     └──► Question Bank
                               reusable individual questions
                ```

                📖 OpenOlat documentation: <a href="https://docs.openolat.org/manual_user/learningresources/" target="_blank" rel="noopener noreferrer">OpenOlat learning resources</a>
                """
            )

        with gr.Accordion("▶ Troubleshooting imports", open=False):
            gr.Markdown(
                """
                ### OpenOlat rejects the ZIP
                Return to QTI-Creator and check the **Validation** result. Fix any reported errors and generate the package again.

                Upload the `.zip` file generated by QTI-Creator directly. **Do not unpack the ZIP before importing it into OpenOlat.**

                ### The test imports, but does not behave as expected
                Preview the test in OpenOlat before publishing the course.

                Also check the settings of the **Test** or **Self-test** course element. OpenOlat provides course-level settings for test behavior and result display in addition to the information stored in the QTI package.

                ### The test is not visible to learners
                Make sure the course and the relevant course element have been published and that the intended participants have access to the course.

                📖 OpenOlat documentation: <a href="https://docs.openolat.org/manual_user/learningresources/Tests_at_course_level/" target="_blank" rel="noopener noreferrer">Tests at course level</a>
                """
            )
